### PR TITLE
fix: remove redundant function call

### PR DESCRIPTION
**Pull request by shaftoe**

### CODE REVIEW

**Review by gr2m — COMMENTED** [review]
A redundant function call would be a function that would be called multiple times, but that isn't the case? I don't mind the change, but this is just a change of style, or am I missing something?

**Comment by shaftoe** [comment]
> A redundant function call would be a function that would be called multiple times, but that isn't the case? I don't mind the change, but this is just a change of style, or am I missing something?

Nah, you're right, it's not improving that much readability / reducing code, I just thought that being a script which is always executing all the logic in `main` when invoked, these few more lines to define a function are not needed.

**Comment by gr2m** [comment]
I'd say we close this PR and use top-level await once it's available across all supported nodejs levels. I think it was added to Node 14, I'm not sure if it was backported to Node 12?

**Comment by shaftoe** [comment]
> I'd say we close this PR and use top-level await once it's available across all supported nodejs levels. I think it was added to Node 14, I'm not sure if it was backported to Node 12?

I'm not sure about the feature backport either, anyway sounds like a good plan. Closing this

**Pull request closed without merging**
