### PR TITLE
chore: Add @MaximDevoir as CODEOWNER

### PR DESCRIPTION
**Pull request by MaximDevoir**
I have been unable to merge PRs - even with maintainer privileges for this repo. I can't see the branch protection settings, but with the presence of a CODEOWNERs file, I'm guessing the option requiring PRs to be reviewed by a  [CODEOWNER](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners) is enabled.

https://help.github.com/en/github/administering-a-repository/enabling-required-reviews-for-pull-requests

### CODE REVIEW

**Comment by gr2m** [comment]
That's odd, we don't have the option enabled. I also don't know why we have a CODEOWNERS file in the first place? @JasonEtco @tcbyrd

**Comment by MaximDevoir** [comment]
Hmm, I'm still not authorized to merge PRs. There must be another [protection rule](https://help.github.com/en/github/administering-a-repository/about-protected-branches#branch-protection-settings) in place preventing me from merging PRs.

> If your repository is owned by an organization, you can restrict users, teams, or apps from pushing to a protected branch. For more information, see "[About branch restrictions](https://help.github.com/en/articles/about-branch-restrictions)."

**Comment by gr2m** [comment]
Ah interesting. We have the "Restrict who can push to matching branches" enabled, I think we wanted to enforce the pull request workflow that way. I wouldn't think that it would prevent you from merging into master.

Let me check in with the others to make sure it's okay to remove that setting, maybe I oversee something

**Comment by gr2m** [comment]
I've removed CODEOWNERS and the "Restrict who can push to matching branches" branch protection setting

**Pull request merged**
