### PR TITLE
feat: add Dockerfile

### LINKED ISSUE #153: add dockerfile to repo
Some integrators are looking for help on how to best run Probot in a public cloud environment. It may help them to have a sample dockerfile for doing this.

### PR DESCRIPTION
**Pull request by FoseFx**
Closes  #153

As you can see I chose to exclude `.env` and `*.pem` files from the containers so no damage is done, when the container ends up publicly available (e.g. on docker hub). This however requires the developer to copy their `APP_ID` and `PRIVATE_KEY` variables (and other variables if desired) and therefore lose the comfort of the .env file. I assume people will deploy their containers using something like docker stack or kubernetes etc.
I dont know if this was the right choice though.

-----
[View rendered templates/basic-js/README.md](https://github.com/FoseFx/create-probot-app/blob/fosefx-docker/templates/basic-js/README.md)
[View rendered templates/basic-ts/README.md](https://github.com/FoseFx/create-probot-app/blob/fosefx-docker/templates/basic-ts/README.md)
[View rendered templates/checks-js/README.md](https://github.com/FoseFx/create-probot-app/blob/fosefx-docker/templates/checks-js/README.md)
[View rendered templates/deploy-js/README.md](https://github.com/FoseFx/create-probot-app/blob/fosefx-docker/templates/deploy-js/README.md)
[View rendered templates/git-data-js/README.md](https://github.com/FoseFx/create-probot-app/blob/fosefx-docker/templates/git-data-js/README.md)

### CODE REVIEW

**Comment by gr2m** [comment]
Thank you @FoseFx for looking into it! @gwestersf any thoughts on Max' questions?

**Comment by FoseFx** [comment]
I guess not?

**Comment by gwestersf** [comment]
Sorry for the late response. Looks good to me.

**Review by gr2m — APPROVED** [review]
🚢📦

**Comment by gr2m** [comment]
> I dont know if this was the right choice though.

We will find out, once people will work with it. Thanks for the great PR 👍🏼

**Comment by gwestersf** [comment]
Thank you!

**Pull request merged**
