### PR TITLE
Fix test scripts to catch every non-zero exit code

### PR DESCRIPTION
**Pull request by shaftoe**

### CODE REVIEW

**Comment by gr2m** [comment]
> Not sure why executing the JS causes explosions though, who's digging into it?

it's a Node 10 problem I think, we can drop Node 10 from testing, I'll do that in a separate PR

**Review by gr2m — APPROVED** [review]
Works as expected now, thanks a lot @shaftoe!

**Comment by shaftoe** [comment]
@gr2m pleasure. How about this PR? do you take care of merging?

**Comment by gr2m** [comment]
Odd, I thought I did, thanks for the ping!

**Pull request merged**
