### PR TITLE
Fix failing tests due to incompatible dependencies

### PR DESCRIPTION
**Pull request by dprothero**
The tests are failing locally. This PR will show whether they are failing in GitHub Actions, as well.

To reproduce the issue locally:

```bash
rm -rf node_modules
npm ci
npm run build
npm test
```

It produces the following error on my MacOS Monterey v12.4 MacBook Pro using Node.js v14.19.2 and v16.15.0 (installed via nvm).

```text
❯ npm test

> create-probot-app@0.0.0-development test
> ./script/test-all-templates.sh

internal/modules/cjs/loader.js:1102
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/dprothero/Projects/create-probot-app/node_modules/inquirer/lib/inquirer.js
require() of ES modules is not supported.
require() of /Users/dprothero/Projects/create-probot-app/node_modules/inquirer/lib/inquirer.js from /Users/dprothero/Projects/create-probot-app/bin/helpers/user-interaction.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename inquirer.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/dprothero/Projects/create-probot-app/node_modules/inquirer/package.json.

    at new NodeError (internal/errors.js:322:7)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1102:13)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/Users/dprothero/Projects/create-probot-app/bin/helpers/user-interaction.js:20:36)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32) {
  code: 'ERR_REQUIRE_ESM'
}
```

-----
[View rendered README.md](https://github.com/dprothero/create-probot-app/blob/failing-tests/README.md)

### CODE REVIEW

**Comment by dprothero** [comment]
Tried downgrading inquirer. Ran into same issue with chalk. Here's where I'm at now:

```
❯ npm test

> create-probot-app@0.0.0-development test
> ./script/test-all-templates.sh

=============================================
simple-git has supported promises / async await since version 2.6.0.
 Importing from 'simple-git/promise' has been deprecated and will be
 removed by July 2022.

To upgrade, change all 'simple-git/promise' imports to just 'simple-git'
=============================================
/Users/dprothero/Projects/create-probot-app/node_modules/npm/index.js:4
  throw new Error('The programmatic API was removed in npm v8.0.0')
  ^

Error: The programmatic API was removed in npm v8.0.0
    at Object.<anonymous> (/Users/dprothero/Projects/create-probot-app/node_modules/npm/index.js:4:9)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/Users/dprothero/Projects/create-probot-app/bin/helpers/run-npm.js:7:31)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/Users/dprothero/Projects/create-probot-app/bin/create-probot-app.js:15:19)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
```

I'll poke around and see where I might go next.

**Comment by dprothero** [comment]
OK, I got it to pass locally. We still have the issue of the shell script not exiting properly which is likely how we got into this situation of incompatible dependencies being automatically updated.

**Comment by gr2m** [comment]
Thanks David! Let's see what @shaftoe comes up with, I'd like to give Alexander a few days to figure out the exit code, but we can also do a follow up issue and merge your changes for now

**Comment by gr2m** [comment]
> I see Node.js 10 is failing due to a different error. Should we just remove testing for unsupported Node versions? That would mean turning off testing for 10, 12, and 15. We should also add 16 and 18.

yes we can just remove node 10

**Comment by gr2m** [comment]
there seems to be a problem with the package lock file, can you update it?

**Comment by dprothero** [comment]
@gr2m Alright, let's see if that does it.

**Comment by gr2m** [comment]
hmm didn't work, would you like me to have a try on your branch? 

You should be able to reproduce the problem locally by running `npm ci`. 

Try resolving it by

```
rm -rf node_modules package-lock.json
npm install
```

**Comment by dprothero** [comment]
Ugh. OK, this should do it. `npm ci` works locally now.

**Pull request merged**
