### PR TITLE
Rewrite application in TypeScript

### LINKED ISSUE #42: `.gitignore` is not created
Hey hey 👋 

I was trying to create a `basic-ts` robawt just now and when I was gonna make the inital git commit it included the `node_modules/` folder. It seems like the `.gitignore` file is not created when using `create-probot-app`. Not sure about other templates then `basic-ts` though.

Here's the output with the `npm install` output omitted:

```sh
☁  koddsson  npx create-probot-app temp

Let's create a Probot app!
Hit enter to accept the suggestion.

? App name: temp
? Description of app: A Probot app
? Author's full name: Kristján Oddsson
? Author's email address: koddsson@gmail.com
? Homepage:
? GitHub user or org name: koddsson
? Repository name: temp
? Which template would you like to use? basic-ts
created file: /Users/kristjanoddsson/koddsson/temp/.env.example
created file: /Users/kristjanoddsson/koddsson/temp/.travis.yml
created file: /Users/kristjanoddsson/koddsson/temp/CODE_OF_CONDUCT.md
created file: /Users/kristjanoddsson/koddsson/temp/CONTRIBUTING.md
created file: /Users/kristjanoddsson/koddsson/temp/LICENSE
created file: /Users/kristjanoddsson/koddsson/temp/README.md
created file: /Users/kristjanoddsson/koddsson/temp/app.yml
created file: /Users/kristjanoddsson/koddsson/temp/jest.config.js
created file: /Users/kristjanoddsson/koddsson/temp/package.json
created file: /Users/kristjanoddsson/koddsson/temp/tsconfig.json
created file: /Users/kristjanoddsson/koddsson/temp/src/index.ts
created file: /Users/kristjanoddsson/koddsson/temp/test/index.test.ts
created file: /Users/kristjanoddsson/koddsson/temp/test/fixtures/issues.opened.json
Finished scaffolding files!

Installing Node dependencies!

npm notice created a lockfile as package-lock.json. You should commit this file.
added 1049 packages from 610 contributors and audited 20747 packages in 19.721s
found 0 vulnerabilities


Done! Enjoy building your Probot app!
☁  koddsson  cat temp/.gitignore
cat: temp/.gitignore: No such file or directory
☁  koddsson
```

### LINKED ISSUE #55: [help wanted] error while installing node dependencies in create-probot-app
it is showing error while installing node dependencies in create-probot-app.
`npm ERR! code ENOLOCAL
npm ERR! Could not install from "" as it does not contain a package.json file.`
so, when i cd to project directory and try `npm install` , still i am getting error.
`npm ERR! Unexpected end of JSON input while parsing near '...:"7.0.0-alpha.18","ba'`.

### LINKED ISSUE #65: A lot of junk files getting generated on create-probot-app
Issue:
A lot of files are getting generated in the working directory instead of under the `node_modules` when using `create-probot-app` with typescript `basic-ts` support.

They all are `cmd` and `sh` files used by node js under the hood when running npm scripts like `npm start` or `npm run build`.

OS: Windows 10

My `./` directory where I ran `create-probot-app` before and after.

Before:
```shell
Phani Rithvij@RithvijL /d/Projects/fun/probotapp
λ ls
- nothing -
```

Command:
```shell
create-probot-app
```

After

```shell
Phani Rithvij@RithvijL /d/Projects/fun/probotapp
λ ls
acorn*              escodegen.cmd   handlebars.cmd            jsesc*            mime*          nodetouch.cmd  rc*         smee.cmd          test/          uuid*
acorn.cmd           esgenerate*     import-local-fixture*     jsesc.cmd         mime.cmd       nopt*          rc.cmd      src/              tsc*           uuid.cmd
app.yml             esgenerate.cmd  import-local-fixture.cmd  json5*            mkdirp*        nopt.cmd       README.md   sshpk-conv*       tsc.cmd        watch*
atob*               eslint*         is-ci*                    json5.cmd         mkdirp.cmd     package.json   rimraf*     sshpk-conv.cmd    tsconfig.json  watch.cmd
atob.cmd            eslint.cmd      is-ci.cmd                 js-yaml*          ncp*           parser*        rimraf.cmd  sshpk-sign*       ts-jest*       which*
bunyan*             esparse*        jest*                     js-yaml.cmd       ncp.cmd        parser.cmd     sane*       sshpk-sign.cmd    ts-jest.cmd    which.cmd
bunyan.cmd          esparse.cmd     jest.cmd                  lib/              node_modules/  probot*        sane.cmd    sshpk-verify*     tsserver*
CODE_OF_CONDUCT.md  esvalidate*     jest.config.js            LICENSE           nodemon*       probot.cmd     semver*     sshpk-verify.cmd  tsserver.cmd
CONTRIBUTING.md     esvalidate.cmd  jest-runtime*             loose-envify*     nodemon.cmd    raven*         semver.cmd  standard*         uglifyjs*
escodegen*          handlebars*     jest-runtime.cmd          loose-envify.cmd  nodetouch*     raven.cmd      smee*       standard.cmd      uglifyjs.cmd
```

It's supposed to be just
```shell
Phani Rithvij@RithvijL /d/Projects/fun/probotapp
λ l
app.yml  CODE_OF_CONDUCT.md  CONTRIBUTING.md  jest.config.js  lib/  LICENSE  node_modules/  package.json  README.md  src/  test/  tsconfig.json
```

Is this the standard file structure or something's wrong here?

### LINKED ISSUE #69: Missing .gitignore file
Hello Probot team;
I've noticed that when generating a bot from a template, the `.gitignore` file is never copied.
Which means that it always has to be added manually after 

This is also related to https://github.com/probot/create-probot-app/issues/42

### LINKED ISSUE #74: Invalid package.json when including quotation marks in author's full name
For example, with name `Kevin "Kassimo" Qian`, I am getting
```
"author": "Kevin "Kassimo" Qian <kevinkassimo@gmail.com>",
```
in generated `package.json`, the quotation marks are not escaped, resulting in a failed npm install. This happens when the author has e.g. a nickname to include.

### LINKED ISSUE #83: TODO | Feature List
## TODOs

Progress is being maintained at #86

### LINKED ISSUE #85: `basic-ts` missing package.json
No `package.json` file is created when selecting `basic-ts` from the template list.

```
$ npx create-probot-app my-first-app
npx: installed 217 in 35.802s

Let's create a Probot app!
Hit enter to accept the suggestion.

? App name: my-first-app
? Description of app: A Probot app
? Author's full name: First Last
? Author's email address: first.last@email.com
? Homepage:

? GitHub user or org name: username
? Repository name: my-first-app
? Which template would you like to use? basic-ts
created file: C:\src\tmp\my-first-app\.env.example
created file: C:\src\tmp\my-first-app\.travis.yml
created file: C:\src\tmp\my-first-app\app.yml
created file: C:\src\tmp\my-first-app\CODE_OF_CONDUCT.md
created file: C:\src\tmp\my-first-app\CONTRIBUTING.md
created file: C:\src\tmp\my-first-app\jest.config.js
created file: C:\src\tmp\my-first-app\LICENSE
created file: C:\src\tmp\my-first-app\package.json
created file: C:\src\tmp\my-first-app\README.md
created file: C:\src\tmp\my-first-app\tsconfig.json
created file: C:\src\tmp\my-first-app\src\index.ts
created file: C:\src\tmp\my-first-app\test\index.test.ts
created file: C:\src\tmp\my-first-app\test\fixtures\issues.opened.json
Finished scaffolding files!

Installing Node dependencies!
npm ERR! code ENOLOCAL
npm ERR! Could not install from "" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\username\AppData\Roaming\npm-cache\_logs\2019-10-15T17_17_45_860Z-debug.log
Could not install npm dependencies. Try running npm install yourself.
```

## Platform

* **OS:** Windows 10 Pro
* DOS or Git Bash terminal

### PR DESCRIPTION
**Pull request by MaximDevoir**
### Final Checklist

- [x] Rebase and fix merge conflicts

### PRs to Merge into this PR

These PRs need to be merged into this PR and closed from their standalone PR.

- [x] Remove `--prefix` and use `cwd` option for spawned processes #80.
- [x] fix: bug where unescaped double-quotes break installation #81.
- [x] fix: Install modules on Windows properly #80.
- [x] fix: Fix `.gitignore` during app initialization #73.
 
### Features

- [x] Check that a `.gitignore` file is being created with test script 00d0a7c35c0989ee681318ddda0ac48012717f0f.
- [x] Remove test support for Node v8 in Travis config (Node v8 is nearing end-of-life) 99982e3c7230f95d6a0e15c46ddced991fea6dcd.
- [x] Create a continuous deployment pipeline (need help from package owners @bkeepers / etc.). See #88.
- [x] (out-of-PR-scope) Use Yarn, if installed, to install packages. Fallback to NPM where Yarn is not installed. Add `--useNPM` and `--useYarn` for user to explicitly set package manager provider.
- [x] (out-of-PR-scope) Update check with `update-notifier` or `update-check`.
- [x] Each `package.json` within templates should have `private` set to `true` efb8f4a893fe0d1b725354c75c06af5c9a053834.
- [x] Include links to Probot documentation at end of app initialization 009db0f15252ad964fdd024cffeb6cb596b4263e.
- [x] Add `--version` flag d87a7bac13883dddb1e220fe39f87216c17cfbac.
- [x] Require `destination` argument in CLI 7769b8803ec3b025182397e0b4db6739b50b5ab2.
- [x] Initialize a git repository at the end an application generation #84.
- [x] Convert application to TypeScript.

### Bugs

- [x] Multiple `-h` options exist. One for `homepage` and one for `help` 6b2e49e0bcc1c96a907166e2e64684f24bae0c7e.
- [x] appName handlebar not being set in template/package.json when supplied with --appName via CLI c332139711eedee27f6b9d0e0c6784fb08129f70.

### Maintenance

- [x] Upgrade project dependencies.

#### Templates

- [x] Remove `.DS_STORE` files f5511e45d8932f9e8a7e33f1013bc7a255bd69b6.
- [x] Upgrade `basic-ts` dependencies 57aeeae280d12104007de727a0e5ef34004c837c.
- [x] Upgrade `basic-js` dependencies de02007822fee6e679af440b4653e1ac93f3ec09.
- [x] Upgrade `check-js` dependencies de02007822fee6e679af440b4653e1ac93f3ec09.
- [x] Upgrade `deploy-js` dependencies de02007822fee6e679af440b4653e1ac93f3ec09.
- [x] Upgrade `git-data-js` dependencies de02007822fee6e679af440b4653e1ac93f3ec09.

## Fixes and Closes

ab982cebd5c176e2ace779c49021cf3f4a44b267 closes #83 
ab982cebd5c176e2ace779c49021cf3f4a44b267 closes #80 and fixes #65
ab982cebd5c176e2ace779c49021cf3f4a44b267 fixes #85 and fixes #55

a433555b5212db4bb318bb1cc820471167487dda closes #73 and fixes #42 and fixes #69 

175c7e69776b55909f11e4000be3aea9c62a19fc closes #81 and fixes #74

c614cf524cf723a9e434796128ba3400fc3f2f3f closes #84

### CODE REVIEW

**Comment by MaximDevoir** [comment]
@JasonEtco  @tcbyrd Here is the application rewrite and upgrade, in all its glory. This checks off probot/probot#1022 `create-probot-app (Type: Core): Needs some love ❤`.

There shouldn't be any breaking changes. Quite the contrary, this PR fixes all open issues and will have a positive downstream effect for repositories like probot/probot - since people won't be using old templates.

Several features were added as part of this upgrade, and I expect it will take some time to review and discuss each addition.

**Comment by MaximDevoir** [comment]
@gr2m Were you able to [get push access](https://github.com/probot/create-probot-app/pull/62#issuecomment-531446951) to the `create-probot-app` module for developing a CD pipeline?

**Comment by gr2m** [comment]
Okay I got it, I can setup the automated releases.

This is a massive PR though, it would be great if more people could have a look at it @tcbyrd @JasonEtco

**Comment by gr2m** [comment]
@MaximDevoir as there was no further feedback, I'm happy to move forward with the PR if you think it's ready, just let me know! I've merged most of the other PRs so there are some conflicts you'd need to resolve :( 

I'll setup a separate PR for the automated releases that we can merge once everything else is ready

**Comment by MaximDevoir** [comment]
PR ready for merging

**Comment by gr2m** [comment]
Could you please resolve the conflcits?

**Comment by MaximDevoir** [comment]
Hmm, everything looks fine. Merging is blocked because I am not authorized to merge this PR (makes sense).

The repository may have branch protections that limit who can merge PRs. Maybe?

**Comment by gr2m** [comment]
Merging works, but I cannot rebase. I don't mind merging this time, but once we have semantic-release setup, it would be nice to keep the commit history clean

**Pull request merged**
