### PR TITLE
Use the standard linter

### PR DESCRIPTION
**Pull request by JasonEtco**
Use the Standard linter, as per https://github.com/probot/probot/issues/235.

Installs the linter, removes `xo` and `eslint-plugin-probot` and fixes all the linting errors/warnings in `create-probot-app.js`.

### CODE REVIEW

**Comment by JasonEtco** [comment]
@bkeepers I don't have write access to this repo :( I must have been kicked from the @probot/maintainers group when :octocat: purged my access to everything. Would you mind merging this in?

**Comment by hiimbex** [comment]
@JasonEtco there's an open invite for you to join back!

**Comment by wilhelmklopp** [comment]
We really need those organization invite Slack notifications 😆

**Comment by JasonEtco** [comment]
@hiimbex I saw that, thanks! I still don't have write access for some reason 🤔

**Comment by bkeepers** [comment]
> I still don't have write access for some reason 🤔

Fixed. Looked like the @probot/maintainers team wasn't added to this repo.

**Comment by JasonEtco** [comment]
Yay thanks @bkeepers! 🎉

**Pull request merged**
