### PR TITLE
feat: add --no-git-init option

### PR DESCRIPTION
**Pull request by shaftoe**
Given that the user already has the faculty to decide in which folder
to create the application, should also be allowed to disable git
initialization too.

### CODE REVIEW

**Review by gr2m — APPROVED** [review]

**Comment by gr2m** [comment]
> Error:  Invalid configuration file `templates/basic-js/app.yml`: JSON Error in /home/runner/work/create-probot-app/create-probot-app/templates/basic-js/package.json: 
> Error:  
> Error:     6 |   "author": "{{{ author }}}",
> Error:     7 |   "license": "ISC",
> Error:  >  8 | {{#if gitInit}}  "repository": "https://github.com/{{ owner }}/{{ repo }}.git",
> Error:       | ^
> Error:     9 |   "homepage": "https://github.com/{{ owner }}/{{ repo }}",
> Error:    10 |   "bugs": "https://github.com/{{ owner }}/{{ repo }}/issues",
> Error:    11 | {{/if}}  "keywords": [
> Error:  
> Error:  Unexpected token { in JSON at position 160 while parsing near '...  "license": "ISC",{{#if gitInit}}  "re...' 
> Error:  
> Error:     6 |   "author": "{{{ author }}}",
> Error:     7 |   "license": "ISC",
> Error:  >  8 | {{#if gitInit}}  "repository": "https://github.com/{{ owner }}/{{ repo }}.git",
> Error:       | ^
> Error:     9 |   "homepage": "https://github.com/{{ owner }}/{{ repo }}",
> Error:    10 |   "bugs": "https://github.com/{{ owner }}/{{ repo }}/issues",
> Error:    11 | {{/if}}  "keywords": [

We can remove the `"repository"` key altogether to make this simple

**Comment by shaftoe** [comment]
I also wonder if the prettier run by the `test` action should just ignore everything under `templates` folder, than add a prettier step in `script/test-template.sh` or elsewhere in `npm run test:template`

**Comment by gr2m** [comment]
> I also wonder if the prettier run by the `test` action should just ignore everything under `templates` folder, than add a prettier step in `script/test-template.sh` or elsewhere in `npm run test:template`

You mean running prettier against the resulting directory, after running the wizzard? The problem is that it might cause false positives and we don't run it against the source. I don't think it's worth it. I'd rather remove the keys as suggested above, or not run prettier on `package.json`

**Review by gr2m — APPROVED** [review]

**Comment by gr2m** [comment]
feel free to merge once CI passes

**Comment by shaftoe** [comment]
Tomorrow I'll add `lint` as pre-commit hook 😇

**Pull request merged**
