### PR TITLE
fix: update for Probot v13

### PR DESCRIPTION
**Pull request by wolfy1339**

### CODE REVIEW

**Review by AaronDewes — APPROVED** [review]
Untested, but looks good.

**Comment by AaronDewes** [comment]
Unrelated, but: @gr2m my invite to this repo expired, can you reinvite me please?

**Comment by gr2m** [comment]
> Unrelated, but: @gr2m my invite to this repo expired, can you reinvite me please?

there you go https://github.com/probot/create-probot-app/invitations

**Comment by AaronDewes** [comment]
I'll test this today and try to fix the tests, then I guess we can merge this.

I want to add the nitro example and would like to move to [isomorphic-git](https://www.npmjs.com/package/isomorphic-git) so we don't have a dependency on git, which could break if git is updated; but I'll do those changes in a separate PR.

**Pull request merged**
