### PR TITLE
update description variable name

### LINKED ISSUE #22: Descriptions are not auto-populated into template
The template files contained within https://github.com/probot/template expect the **description** information to be contained in `description`, ie:

```
{
  "name": "{{ name }}",
  "version": "1.0.0",
  "description": "{{{ description }}}",
  "author": "{{{ author }}}",
```
https://github.com/probot/template/blob/011af1fe2095ea3eeec84553c7d4781378b59540/package.json#L1-L5

while the create script stores it under the variable `desc` , ie:
https://github.com/probot/create-probot-app/blob/aefa4b695a80c28be7d53cef468e59cf8288d96d/bin/create-probot-app.js#L47-L55

Wasn't sure if I should open the PR here or in the template repo.

### PR DESCRIPTION
**Pull request by jbjonesjr**
fixes #22

### CODE REVIEW

**Comment by bkeepers** [comment]
vs on master:

```
$ bin/create-probot-app.js wat   
Let's create a Probot app!
? App name: wat
? Description of app: (A Probot app) 
…
```

**Comment by jbjonesjr** [comment]
so weird.... i'll play around more with this to see what could be up

**Comment by jbjonesjr** [comment]
initial testing seems to show that `description` is a magic word within the commander module (_program in this code_).

Sample [[npmjs.com/package/commander](https://www.npmjs.com/package/commander#examples)]:
``` javascript
program
  .command('setup [env]')
  .description('run setup commands for all envs')
  .option("-s, --setup_mode [mode]", "Which setup mode to use")
  .action(function(env, options){
...
```

At the end of the day, it's the answers hash provided by the `inquirer` package that is used by the template, so as long as that is named `description`, downstream should work.

**Comment by jbjonesjr** [comment]
ran tests locally, looks like the description is now in the README.md and the package.json file. LGTM.

**Comment by bkeepers** [comment]
Thanks!

**Pull request merged**
