### PR TITLE
Greenkeeper/default/probot 9.0.1

### PR DESCRIPTION
**Pull request by gr2m**

### CODE REVIEW

**Comment by decompil3d** [comment]
This bit me in the ass today -- couldn't figure out why the API surface on my app didn't match what I saw in code in Probot's github. Then ran `npm outdated` and sure enough it was on 7.5.1 instead of 9.0.2.

**Comment by gr2m** [comment]
same :( sorry! We have to get the tests fixed before we can merge this. Help welcome!

**Comment by decompil3d** [comment]
@gr2m I see the bug -- I'll try to make a PR to this branch soon with a fix.

**Comment by decompil3d** [comment]
@gr2m Here you go: https://github.com/probot/create-probot-app/pull/62

**Pull request merged**
